name: CI

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ develop ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Provide default env for non-prod builds
        run: |
          if [ ! -f .env ] && [ -f .env.example ]; then
            cp .env.example .env
          fi

      - name: Install dependencies
        run: |
          yarn --version
          yarn install --frozen-lockfile || yarn install

      - name: Lint (non-blocking)
        run: |
          yarn lint || echo "Lint errors detected (non-blocking for PR)"
        continue-on-error: true

      - name: Build
        run: yarn build

